### ISSUE TITLE
foreman.version should be part of gemfile.lock artifact name

### ISSUE THREAD

**Issue by dosas** [theforeman/actions#43]
When running the action against multiple forman versions: https://github.com/ATIX-AG/foreman_snapshot_management/actions/runs/7976082116/job/21775830193?pr=98
```
 strategy:
      fail-fast: false
      matrix:
        foreman:
          - 3.9-stable
          - develop
```

I get the following error
```
Archive Gemfile.lock
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

IMHO `${{ inputs.foreman_version }}` should be included in the artifact name https://github.com/theforeman/actions/blob/v0/.github/workflows/foreman_plugin.yml#L115

Happy to create a PR
